server:
  servlet:
    context-path: /api
  port: 80

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/professores
    username: root
    password:
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  messages:
    encoding: UTF-8
    basename:
  flyway:
    enabled: true
    locations: classpath:db/migrations
  docker:
    compose:
      file: ./professores-disponibilidades/compose.yaml
  web:
    locale: pt_BR
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/imepac
          jwk-set-uri: http://localhost:8080/realms/imepac/protocol/openid-connect/certs
flyway:
  url: jdbc:mysql://localhost:3306/professores
  user: root
  password: